---
- name: Consultar uptime y enviar por correo
  hosts: localhost
  gather_facts: no
  vars:
    uptime_url: "http://10.110.0.116/infoprepost/uptime.php"
    output_file: "/tmp/uptime_status.html"
    subject: "Reporte de Uptime"
    email_host: "172.22.88.6"
    email_port: 25
    email_from: "edduin.arias.Ext@claro.com.co"
    email_to: "edduin.arias.Ext@claro.com.co"
    email_cc: "gdi_admunix@claro.com.co"

  tasks:
    - name: Obtener contenido desde la URL
      uri:
        url: "{{ uptime_url }}"
        method: GET
        return_content: yes
      register: web_response

    - name: Guardar contenido HTML en archivo temporal
      copy:
        content: "{{ web_response.content }}"
        dest: "{{ output_file }}"

    - name: Enviar correo con el reporte de uptime (HTML)
      mail:
        host: "{{ email_host }}"
        port: "{{ email_port }}"
        subject: "{{ subject }}"
        subtype: html
        body: "{{ lookup('file', output_file) }}"
        from: "{{ email_from }}"
        to: "{{ email_to }}"
      delegate_to: lnxadmux01
      run_once: yes
      tags:
        - envio_uptime
